"""Generate suite.bend from vendor/zig-std-json/JSONTestSuite_test.zig."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "vendor/zig-std-json/JSONTestSuite_test.zig"
OUT = ROOT / "suite.bend"

# cases built from Zig expressions, written here as Bend expressions
SPECIAL = {
    "i_structure_500_nested_arrays.json": ("Y", 'rep(500n, "[") ++ rep(500n, "]")'),
    "n_structure_100000_opening_arrays.json": ("N", 'rep(100000n, "[")'),
    "n_structure_open_array_object.json": ("N", 'rep(50000n, "[{\\"\\":") ++ "\\n"'),
}

WANT = {"ok": "Y", "err": "N"}


# JSONTestSuite leaves i_ cases to the parser; bjson's answers:
# - numbers of any size or exponent parse: they keep their exact digits
# - a lone or out-of-order UTF-16 surrogate escape fails (LoneSurrogate)
# - input that is not UTF-8 fails (InvalidUtf8), UTF-16 included
# - 500 levels of nesting and a leading BOM parse
def decided(name, want):
    if want != "any":
        return WANT[want]
    return "Y" if name.startswith(("i_number_", "i_structure_")) else "N"


def zig_bytes(lit):
    out, i = bytearray(), 0
    while i < len(lit):
        c = lit[i]
        if c != "\\":
            out += c.encode()
            i += 1
            continue
        e = lit[i + 1]
        if e == "x":
            out.append(int(lit[i + 2:i + 4], 16))
            i += 4
        elif e == "u":
            j = lit.index("}", i)
            out += chr(int(lit[i + 3:j], 16)).encode()
            i = j + 1
        else:
            out += {"n": b"\n", "r": b"\r", "t": b"\t", "\\": b"\\", '"': b'"', "'": b"'"}[e]
            i += 2
    return bytes(out)


def bend_lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif 0x20 <= o < 0x7F:
            out.append(ch)
        else:
            out.append("\\u{%X}" % o)
    return '"' + "".join(out) + '"'


def main():
    text = SRC.read_text()
    cases, skipped = [], []
    for m in re.finditer(r'test "([^"]+)" \{\n(.*?)\n\}', text, re.S):
        name, body = m.group(1), m.group(2)
        if name in SPECIAL:
            want, expr = SPECIAL[name]
            cases.append((name, want, expr))
            continue
        lit = re.fullmatch(r'\s*try (ok|err|any)\("((?:[^"\\]|\\.)*)"\);', body)
        if not lit:
            sys.exit(f"unhandled case: {name}")
        raw = zig_bytes(lit.group(2))
        try:
            s = raw.decode("utf-8")
        except UnicodeDecodeError:
            # not text: goes in as bytes, and must fail as invalid UTF-8
            cases.append((name, "B", "[" + ", ".join(map(str, raw)) + "]"))
            continue
        cases.append((name, decided(name, lit.group(1)), bend_lit(s)))

    lines = [
        "# generated by scripts/gen_suite.py from JSONTestSuite; do not edit",
        "import Base",
        "import ./suite_run.bend as S",
        "",
        "def rep.go(n: Nat, +s: String, acc: String) -> String:",
        "  match n:",
        "    case 0n:",
        "      acc",
        "    case 1n+p:",
        "      rep.go(p, s, s ++ acc)",
        "",
        "def rep(n: Nat, s: String) -> String:",
        '  rep.go(n, s, "")',
        "",
        "def cases() -> List<&2, S.Case>:",
        "  [",
    ]
    for i, (name, want, expr) in enumerate(cases):
        sep = "," if i < len(cases) - 1 else ""
        if want == "B":
            lines.append(f'    S.Bytes{{"{name}", {expr}}}{sep}')
        else:
            lines.append(f'    S.Case{{"{name}", S.{want}{{}}, {expr}}}{sep}')
    lines += [
        "  ]",
        "",
        "def main() -> IO(Unit):",
        "  S.run(cases())",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"{len(cases)} cases -> {OUT.name}")


main()
